"""The state a tier 2 run starts from.

The per-test reset restores what a test changed, which is not the same as starting from a
known cluster: it captures each Secret as it finds it at setup, so a run that dies mid-test
leaves its mess behind and every run after it adopts that mess as its baseline and
faithfully preserves it. CI never sees this -- each shard gets a fresh kind cluster -- so
the only thing standing between a local run and a false result is this.
"""

import pytest

from app.adapters.kubernetes import RealKubernetes
from app.config import Settings
from tests.tier2.conftest import (
    CATALOG_SEED_SECRET,
    _divergence,
    _restore_baseline,
    kubectl,
    manifest_secrets,
)

pytestmark = pytest.mark.tier2


def test_the_manifests_are_the_baseline(settings: Settings) -> None:
    """Read from `deploy/trino-dev` rather than restated here. Two of those files are
    generated by scripts with CI drift gates, so a copy kept in the tests would be a third
    truth to keep in step."""
    secrets = manifest_secrets()

    assert CATALOG_SEED_SECRET in secrets
    assert sorted(secrets[CATALOG_SEED_SECRET]) == ["tpch.properties"]
    assert secrets["trino-event-listener"] == {}, "empty, and not absent"


def test_the_suite_starts_from_what_the_manifests_ship(settings: Settings) -> None:
    """Whatever the last run did, this one begins here."""
    assert _divergence(settings) == []


async def test_a_clean_cluster_is_left_alone(
    settings: Settings, real_kubernetes: RealKubernetes
) -> None:
    """The restore ends in a coordinator restart. Paying that on every run would make the
    whole suite slower to avoid a problem it does not have."""
    before = await real_kubernetes.rollout_state("trino-coordinator")

    assert _divergence(settings) == [], "already at baseline, so nothing to do"

    after = await real_kubernetes.rollout_state("trino-coordinator")
    assert after.generation == before.generation, "the pod template was never touched"


def test_a_cluster_a_dead_run_dirtied_is_detected_and_restored(settings: Settings) -> None:
    """Exactly what happened twice: a killed run left a catalog in the seed Secret, and
    every later run preserved it. The suite has to notice and fix it, not inherit it.

    Deliberately not using the per-test reset: restoring the baseline restarts the
    coordinator, and that fixture's own teardown wants a live connection to put catalogs
    back. This test leaves the cluster at baseline itself, which is all that reset would
    have achieved.
    """
    kubectl(
        "patch",
        "secret",
        CATALOG_SEED_SECRET,
        "--type=merge",
        "-p",
        '{"stringData":{"kept.properties":"connector.name=memory\\n"}}',
    )

    assert f"secret {CATALOG_SEED_SECRET}" in _divergence(settings)

    _restore_baseline(settings)

    assert _divergence(settings) == []
