"""Writes the bootstrap access-control Secret to deploy/trino-dev.

Apchi generates this file and rewrites it on every Apply, so it must not be
hand-maintained here -- a hand-written copy drifts from what Apchi produces and nobody
notices until a rule stops doing what the repo says.

It cannot simply be absent, either: Trino reads `security.config-file` at startup and
refuses to boot without it ("Configuration is invalid", with the pod going to Failed),
so the coordinator could not start before Apchi had run once. Committing the generated
output keeps the Cluster able to start on its own -- the same property §7.1 wants for
catalogs -- and the CI drift check keeps it honest.
"""

import sys
from pathlib import Path

from app.config import Settings
from app.pipeline.access_control import RULES_KEY, render_rules

TARGET = Path(__file__).resolve().parent.parent / "deploy" / "trino-dev" / "05-access-control.yaml"


def render() -> str:
    settings = Settings()
    rules = render_rules(settings.trino_user).rstrip("\n")
    indented = "\n".join(f"    {line}" for line in rules.splitlines())
    return f"""# Generated by scripts/export_access_control.py. Do not edit.
#
# Apchi rewrites this Secret on every Apply. It is committed only so the coordinator can
# start before Apchi has ever run: Trino refuses to boot without the file. CI fails if
# this differs from what Apchi generates.
apiVersion: v1
kind: Secret
metadata:
  name: {settings.access_control_secret_name}
stringData:
  {RULES_KEY}: |
{indented}
"""


def main() -> int:
    rendered = render()
    if "--check" in sys.argv:
        if not TARGET.exists():
            print(
                f"{TARGET.name} is missing; run scripts/export_access_control.py", file=sys.stderr
            )
            return 1
        if TARGET.read_text() != rendered:
            print(
                f"{TARGET.name} does not match what Apchi generates. Regenerate it and "
                "commit the result so the change is reviewed.",
                file=sys.stderr,
            )
            return 1
        return 0
    TARGET.write_text(rendered)
    print(f"wrote {TARGET.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
