"""Writes the bootstrap user-mapping Secret to deploy/trino-dev.

The same bargain as the access-control rules, for the same reason. Apchi rewrites this
Secret whenever the Certificate Mapping Pattern changes, so hand-maintaining it here would
let the repo and the generator drift apart unnoticed.

And it cannot be left out: the coordinator is configured with a user-mapping file, and
Trino refuses to start when the file it was told to read is missing. Committing the
generated output -- the reserved rule for Apchi's own identity, then the rule that leaves
every other name as presented -- keeps the Cluster able to start before Apchi has run, and
the CI drift check keeps the copy honest.
"""

import sys
from pathlib import Path

from app.config import Settings
from app.sections.certificate_mapping.generator import FILE_KEY, render_rules

TARGET = Path(__file__).resolve().parent.parent / "deploy" / "trino-dev" / "06-user-mapping.yaml"


def render() -> str:
    settings = Settings()
    rules = render_rules({}, settings.trino_user).rstrip("\n")
    indented = "\n".join(f"    {line}" for line in rules.splitlines())
    return f"""# Generated by scripts/export_user_mapping.py. Do not edit.
#
# Apchi rewrites this Secret whenever the Certificate Mapping Pattern changes. It is
# committed only so the coordinator can start before Apchi has ever run: Trino refuses to
# boot without the file. CI fails if this differs from what Apchi generates.
apiVersion: v1
kind: Secret
metadata:
  name: {settings.certificate_mapping_secret_name}
stringData:
  {FILE_KEY}: |
{indented}
"""


def main() -> int:
    rendered = render()
    if "--check" in sys.argv:
        if not TARGET.exists():
            print(f"{TARGET.name} is missing; run scripts/export_user_mapping.py", file=sys.stderr)
            return 1
        if TARGET.read_text() != rendered:
            print(
                f"{TARGET.name} does not match what Apchi generates. Regenerate it and "
                "commit the result so the change is reviewed.",
                file=sys.stderr,
            )
            return 1
        return 0
    TARGET.write_text(rendered)
    print(f"wrote {TARGET.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
