"""Writes the bootstrap access-control rules, for every deployment that ships one.

Apchi generates this file and rewrites it on every Apply, so it must not be
hand-maintained here -- a hand-written copy drifts from what Apchi produces and nobody
notices until a rule stops doing what the repo says.

It cannot simply be absent, either: Trino reads `security.config-file` at startup and
refuses to boot without it ("Configuration is invalid", with the pod going to Failed),
so the coordinator could not start before Apchi had run once. Committing the generated
output keeps the Cluster able to start on its own -- the same property §7.1 wants for
catalogs -- and the CI drift check keeps it honest.
"""

import sys
from pathlib import Path

from app.config import Settings
from app.sections.permissions.generator import RULES_KEY, render_rules

ROOT = Path(__file__).resolve().parent.parent
#: The reference deployment's Secret, manifest and all.
TARGET = ROOT / "deploy" / "trino-dev" / "05-access-control.yaml"
#: The same rules as a bare file, for the chart's pre-install hook to read with
#: `.Files.Get`. Two consumers, one generator -- a second hand-maintained copy is the
#: thing this script exists to prevent.
CHART_TARGET = ROOT / "charts" / "trino" / "files" / "rules.json"


def rules() -> str:
    return render_rules(Settings().trino_user).rstrip("\n") + "\n"


def render() -> str:
    settings = Settings()
    indented = "\n".join(f"    {line}" for line in rules().rstrip("\n").splitlines())
    return f"""# Generated by scripts/export_access_control.py. Do not edit.
#
# Apchi rewrites this Secret on every Apply. It is committed only so the coordinator can
# start before Apchi has ever run: Trino refuses to boot without the file. CI fails if
# this differs from what Apchi generates.
apiVersion: v1
kind: Secret
metadata:
  name: {settings.access_control_secret_name}
stringData:
  {RULES_KEY}: |
{indented}
"""


def main() -> int:
    outputs = {TARGET: render(), CHART_TARGET: rules()}
    if "--check" in sys.argv:
        for target, expected in outputs.items():
            if not target.exists():
                print(
                    f"{target.name} is missing; run scripts/export_access_control.py",
                    file=sys.stderr,
                )
                return 1
            if target.read_text() != expected:
                print(
                    f"{target.name} does not match what Apchi generates. Regenerate it and "
                    "commit the result so the change is reviewed.",
                    file=sys.stderr,
                )
                return 1
        return 0
    for target, content in outputs.items():
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        print(f"wrote {target.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
